// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvitrtscqqargzpiyvxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2aXRydHNjcXFhcmd6cGl5dnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMjEzMzEsImV4cCI6MjA2Mjc5NzMzMX0.8Bmhsy2WwcBzdJsAvrDq95LAQZDVMHmC786uWNxw-vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);